name: build

on:
  push:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get URL
        run: |
          sha12hex() {
            echo $(base64 -d <<< $1 | od -An -vt x1 | tr -d '\n ')
          }
          processing(){
            body='<?xml version="1.0" encoding="UTF-8"?><request protocol="3.0" version="1.3.23.9" shell_version="1.3.21.103" ismachine="0" sessionid="{3597644B-2952-4F92-AE55-D315F45F80A5}" installsource="ondemandcheckforupdate" requestid="{CD7523AD-A40D-49F4-AEEF-8C114B804658}" dedup="cr"><hw sse="1" sse2="1" sse3="1" ssse3="1" sse41="1" sse42="1" avx="1" physmemory="12582912" /><os platform="win" version="6.3" arch="'$1'" /><app appid="{8A69D345-D564-463C-AFF1-A69D9E530F96}" ap="'$2'"><updatecheck /></app></request>'
            resp=$(curl -sX POST https://tools.google.com/service/update2 -H "Content-Type: application/xml"  -d "$body")
            regex="(https://dl\.google\.com[^\"]+).* run=\"([^\"]+).* Version=\"([^\"]+).* hash=\"([^\"]+)\" hash_sha256=\"([^\"]+)"
            [[ $resp =~ $regex ]] && echo ${BASH_REMATCH[1]}${BASH_REMATCH[2]} > $1.txt && echo "RELEASE_TITLE=${BASH_REMATCH[3]}" >> $GITHUB_ENV
          }
          RELEASE_DESC="$(processing x64 x64-stable-multi-chrome)"
          RELEASE_DESC+="
          line break
          test"
          echo "RELEASE_DESC=\"$RELEASE_DESC\"" >> "$GITHUB_ENV"
      - name: Update Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: stable_latest
          prerelease: true
          name: "${{ env.RELEASE_TITLE }}"
          body: "${{ env.RELEASE_DESC }}"
          files: |
            x64.txt
            x86.txt